#!/usr/bin/env python3
"""练习 013 的题目数据（Day01 大模型提示词工程）。"""

choices = [
    {'qid': 1, 'question': '人工智能发展的三个核心驱动力是？', 'options': ['数据、算法、算力', '电脑、鼠标、键盘', '前端、后端、数据库', '图片、视频、音频'], 'answer': 'A', 'analysis': 'AI 的三大核心驱动力是数据（训练素材）、算法（模型架构）和算力（计算资源）。'},
    {'qid': 2, 'question': '关于提示词的说法，正确的是？', 'options': ['提示词只等于用户最后输入的问题', '提示词可以包含角色、规则、资料、示例和输出格式', '提示词越短越好，不能写长', '提示词只在网页聊天中有用，代码调用时没有用'], 'answer': 'B', 'analysis': '提示词不仅包含用户问题，还可以包含角色设定、业务规则、参考资料、示例和输出格式等。'},
    {'qid': 3, 'question': '下面哪种情况更像事实性幻觉？', 'options': ['要求只输出 JSON，模型多输出解释', '模型把不存在的公司新闻说成真实发生', '模型回复太长', '模型没有使用表格'], 'answer': 'B', 'analysis': '事实性幻觉指模型生成的内容与现实事实不一致，如编造不存在的事件、人物或时间。'},
    {'qid': 4, 'question': '下面哪种情况更像忠实性幻觉？', 'options': ['模型没有遵守"只输出 JSON"的要求', '模型说了一个错误年份', '模型编造了不存在的人名', '模型把别人的作品说成某歌手作品'], 'answer': 'A', 'analysis': '忠实性幻觉指模型没有遵守用户指令或上下文要求，如要求只输出 JSON 却额外输出解释。'},
    {'qid': 5, 'question': 'RAG 更适合解决什么问题？', 'options': ['让模型改变底层参数', '让模型检索外部资料后再回答', '让模型自动点击网页', '让模型不需要提示词'], 'answer': 'B', 'analysis': 'RAG（检索增强生成）通过检索外部资料后交给模型回答，类似"开卷考试"。'},
    {'qid': 6, 'question': '微调更像下面哪种说法？', 'options': ['给模型一份临时参考资料', '让模型回炉深造，长期学习某类能力', '让模型调用天气接口', '让模型把回答变短'], 'answer': 'B', 'analysis': '微调是对模型进行二次训练或参数调整，让模型长期适配某类任务，类似"回炉深造"。'},
    {'qid': 7, 'question': 'Agent 的核心理解是？', 'options': ['模型只负责生成图片', '模型做决策，程序负责调用工具执行', '模型不能和程序结合', 'Agent 等于普通聊天窗口'], 'answer': 'B', 'analysis': 'Agent 的核心是模型负责决策和推理，程序负责调用工具执行具体操作。'},
    {'qid': 8, 'question': '在 messages 中，system 角色主要用于？', 'options': ['提供模型身份、规则和输出边界', '表示用户本次提问', '表示数据库连接', '表示 Python 文件名'], 'answer': 'A', 'analysis': 'system 角色用于设定模型的身份、任务规则和输出边界，是提示词工程的核心。'},
    {'qid': 9, 'question': 'API Key 的正确使用方式是？', 'options': ['直接写进代码并发给同学', '截图发到群里方便大家复制', '放到环境变量或安全配置中读取', '随便写一个字符串即可'], 'answer': 'C', 'analysis': 'API Key 是账户密钥，应放到环境变量或安全配置中读取，不能写进公开代码。'},
    {'qid': 10, 'question': '为什么很多 AI 项目要求模型输出 JSON？', 'options': ['JSON 看起来更复杂', 'JSON 方便程序继续解析和处理', 'JSON 只能给人阅读', 'JSON 可以自动训练模型'], 'answer': 'B', 'analysis': 'JSON 字段固定、格式规范，程序容易解析，可以继续写入数据库、传给前端或进入工作流。'},
]

fills = [
    {'qid': 11, 'question': 'AI 能力的三个核心驱动力是________、________、________。', 'answer': '数据、算法、算力', 'analysis': '数据提供训练素材，算法定义模型架构，算力提供计算资源，三者缺一不可。'},
    {'qid': 12, 'question': '大模型幻觉可以分为________幻觉和________幻觉。', 'answer': '事实性、忠实性', 'analysis': '事实性幻觉是编造不存在的事实；忠实性幻觉是不遵守用户指令或上下文要求。'},
    {'qid': 13, 'question': '提示词包含用户问题，但不等于________。', 'answer': '用户问题', 'analysis': '提示词除了用户问题，还可能包含角色设定、业务背景、参考资料、示例等。'},
    {'qid': 14, 'question': 'RAG 可以用"________ 考试"来类比，因为它会给模型提供外部资料。', 'answer': '开卷', 'analysis': 'RAG 在回答前先检索外部资料，类似开卷考试可以翻书找答案。'},
    {'qid': 15, 'question': '微调可以理解为让模型________，从而长期适配某类任务。', 'answer': '回炉深造', 'analysis': '微调通过二次训练调整模型参数，让模型长期学习某类能力。'},
    {'qid': 16, 'question': 'Agent 中，模型主要负责________，程序主要负责________。', 'answer': '决策、调用工具执行', 'analysis': 'Agent 的分工：模型负责推理和决策，程序负责调用具体工具执行操作。'},
    {'qid': 17, 'question': 'messages 中常见的三个角色是________、________、________。', 'answer': 'system、user、assistant', 'analysis': 'system 设定规则，user 提出问题，assistant 表示模型回复或提供示例。'},
    {'qid': 18, 'question': 'system 角色通常用于设定模型的身份、任务规则和________。', 'answer': '输出边界', 'analysis': 'system 角色定义模型"是谁"、"做什么"、"输出什么格式"，是提示词工程的核心。'},
    {'qid': 19, 'question': 'API Key 不应该写进公开代码，推荐放到________中。', 'answer': '环境变量', 'analysis': '环境变量是安全存储密钥的标准方式，避免密钥泄露。'},
    {'qid': 20, 'question': '如果希望程序更容易处理模型结果，可以要求模型输出________格式。', 'answer': 'JSON', 'analysis': 'JSON 字段固定、格式规范，程序容易解析，是 AI 项目最常用的输出格式。'},
]

shorts = [
    {'qid': 21, 'question': '为什么说提示词不是简单的一句用户提问？', 'reference': '因为真实提示词除了用户问题，还可能包含角色设定、业务背景、参考资料、示例、步骤、输出格式和边界规则。用户问题只是提示词的一部分。'},
    {'qid': 22, 'question': '请用自己的话解释事实性幻觉。', 'reference': '事实性幻觉指模型生成的内容和现实事实不一致，比如编造不存在的事件、人物、作品或时间。'},
    {'qid': 23, 'question': '请用自己的话解释忠实性幻觉。', 'reference': '忠实性幻觉指模型没有遵守用户指令或上下文要求，比如要求只输出 JSON，它却额外输出解释。'},
    {'qid': 24, 'question': 'RAG 和微调有什么区别？', 'reference': 'RAG 是检索外部资料后交给模型回答，像开卷考试；微调是对模型进行二次训练或参数调整，让模型长期适配某类任务。'},
    {'qid': 25, 'question': '为什么工作中经常要求模型输出 JSON？', 'reference': '因为 JSON 字段固定，程序容易解析，可以继续写入数据库、传给前端或进入工作流。'},
    {'qid': 26, 'question': 'system、user、assistant 三种角色分别有什么作用？', 'reference': 'system 用来设定规则和边界；user 用来提出具体问题；assistant 表示模型回复，常用于提供示例答案。'},
    {'qid': 27, 'question': '为什么 API Key 不能直接写在代码里？', 'reference': '因为 API Key 相当于账户钥匙，泄露后别人可能消耗额度或造成安全风险。应该放到环境变量或安全配置中读取。'},
    {'qid': 28, 'question': '请列出一个清晰提示词应该包含的 4 个要素。', 'reference': '可以包含角色、任务、背景、约束、输出格式、示例、参考资料等，答出其中 4 个即可。'},
    {'qid': 29, 'question': '什么情况下适合给模型提供示例？', 'reference': '当希望模型模仿固定格式、风格、分类标准或输出结构时，适合提供示例。'},
    {'qid': 30, 'question': '为什么复杂任务要拆成多个步骤再交给模型？', 'reference': '因为复杂任务一次性提交容易让模型遗漏步骤或误解意图，拆步骤可以降低难度，让模型按流程完成任务。'},
]

writes = [
    {'qid': 31, 'title': '基础练习：调用模型完成一句话解释', 'desc': '使用 OpenAI 兼容方式调用模型，从环境变量读取 OPENAI_API_KEY，提问"请用一句话解释提示词工程"，打印模型回复。', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": "你是一个简洁的 AI 助手，请用中文回答。"},\n        {"role": "user", "content": "请用一句话解释提示词工程。"}\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
    {'qid': 32, 'title': '基础练习：设置计算器角色', 'desc': '使用 system 设定模型为计算器（只输出最终结果，不要解释），user 中提问 2 + 5 * 3 等于多少？', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": "你是一个计算器，只输出最终计算结果，不要解释过程。"},\n        {"role": "user", "content": "2 + 5 * 3 等于多少？"}\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
    {'qid': 33, 'title': '基础练习：DashScope 调用模型', 'desc': '使用 dashscope 库调用模型，从环境变量读取 DASHSCOPE_API_KEY，提问"请用一句话解释 RAG"。', 'reference': 'import os\nimport dashscope\n\ndashscope.api_key = os.getenv("DASHSCOPE_API_KEY")\nif not dashscope.api_key:\n    raise ValueError("没有读取到 DASHSCOPE_API_KEY，请配置环境变量后重启 PyCharm。")\n\nresponse = dashscope.Generation.call(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": "你是一个简洁的 AI 助手，请用中文回答。"},\n        {"role": "user", "content": "请用一句话解释 RAG。"}\n    ]\n)\n\nprint(response.output["text"])'},
    {'qid': 34, 'title': '进阶练习：客户反馈情绪分类', 'desc': '使用 system 设定模型为客户反馈分析助手，输入客户反馈，要求输出 JSON（emotion/problem/suggestion），情绪只能是正面、负面、中性。', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\nsystem_prompt = """\n你是一个客户反馈分析助手。\n请分析用户反馈，并输出 JSON。\n\n要求：\n1. emotion 只能是：正面、负面、中性。\n2. problem 提取客户提到的主要问题。\n3. suggestion 给出一句适合客服回复的建议。\n4. 只输出 JSON，不要输出解释文字。\n"""\n\nuser_feedback = """\n这个 AI 写作工具生成速度挺快，但是经常答非所问，导出的格式也有点乱。\n"""\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": system_prompt},\n        {"role": "user", "content": user_feedback},\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
    {'qid': 35, 'title': '进阶练习：会议行动项提取', 'desc': '从会议内容中提取行动项，输出 JSON，每个行动项包含 item/owner/deadline，没有明确截止时间则 deadline 写 null。', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\nsystem_prompt = """\n你是一个会议行动项提取助手。\n请从会议内容中提取明确有人负责的任务。\n\n输出要求：\n1. 只输出 JSON。\n2. JSON 顶层字段为 action_items。\n3. 每个行动项包含 item、owner、deadline。\n4. 如果没有明确截止时间，deadline 写 null。\n"""\n\nmeeting_text = """\n本次周会决定，小王本周五前完成智能客服原型页面，小张负责整理客户反馈，但没有明确截止时间。\n"""\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": system_prompt},\n        {"role": "user", "content": meeting_text},\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
    {'qid': 36, 'title': '进阶练习：给模型一个示例', 'desc': '使用 few-shot 示例，让模型学习快递信息抽取。system 设定规则，user/assistant 提供示例，再输入真实文本，输出姓名/手机号/地址 JSON。', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\nsystem_prompt = """\n你是一个快递信息提取助手。\n请提取姓名、手机号、地址。\n只输出 JSON。\n手机号中的横线和空格要去掉。\n"""\n\nexample_user = "张明远，138-1234-5678\n广东省深圳市南山区科技园南区高新南一道1000号腾讯大厦18层 1806室"\n\nexample_assistant = \'{"name": "张明远", "phone": "13812345678", "address": "广东省深圳市南山区科技园南区高新南一道1000号腾讯大厦18层 180室"}\'\n\nreal_user = """\n李婉婷\n151-9876-5432\n北京市海淀区中关村大街1号海龙大厦8层805室\n东西是一份文件，已经封装好了。\n"""\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": system_prompt},\n        {"role": "user", "content": example_user},\n        {"role": "assistant", "content": example_assistant},\n        {"role": "user", "content": real_user},\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
    {'qid': 37, 'title': '综合案例：社媒内容分类', 'desc': '设计社媒内容分类提示词，将输入内容分为噪音/广告营销/弱相关/非噪音四类，要求输出 JSON（label + confidence）。', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\nsystem_prompt = """\n你是一个品牌社媒内容分类助手。\n\n请将输入内容分类为以下四类之一：\n1. 噪音：完全无关，比如成语、误匹配、人名等。\n2. 广告营销：促销、打卡、优惠、正面分享。\n3. 弱相关：只是顺带提到品牌，没有具体行为或评价。\n4. 非噪音：真实评价、投诉、体验、负面内容或有效内容。\n\n输出要求：\n1. 只输出 JSON。\n2. label 必须是：噪音、广告营销、弱相关、非噪音。\n3. confidence 必须是：high、medium、low。\n"""\n\ncontent = "#海底捞# 今天生日去吃饭，服务员送了蛋糕，体验很好！"\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": system_prompt},\n        {"role": "user", "content": content},\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
    {'qid': 38, 'title': '综合案例：AI 产品需求整理', 'desc': '从需求描述中提取结构化信息，输出 JSON（product/scenario/channels/constraints/risk_handling）。', 'reference': 'import os\nfrom openai import OpenAI\n\napi_key = os.getenv("OPENAI_API_KEY")\nif not api_key:\n    raise ValueError("没有读取到 OPENAI_API_KEY，请配置环境变量后重启 PyCharm。")\n\nclient = OpenAI(\n    api_key=api_key,\n    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",\n)\n\nsystem_prompt = """\n你是一个 AI 产品需求分析助手。\n请从用户输入中提取结构化需求信息。\n\n输出 JSON，字段包括：\n1. product：产品名称或产品类型。\n2. scenario：主要应用场景。\n3. channels：使用渠道，数组格式。\n4. constraints：约束条件，数组格式。\n5. risk_handling：风险处理方式。\n\n只输出 JSON，不要输出解释文字。\n"""\n\nrequirement = """\n我们想做一个 AI 客服助手，主要用于回答用户关于订单、退款、物流的问题。\n希望先接入网页端，输出要简洁，遇到不确定的问题要提示转人工。\n"""\n\ncompletion = client.chat.completions.create(\n    model="qwen-plus",\n    messages=[\n        {"role": "system", "content": system_prompt},\n        {"role": "user", "content": requirement},\n    ]\n)\n\nprint(completion.choices[0].message.content)'},
]
