#!/usr/bin/env python3
"""所有练习的元数据配置。新增练习只需在此添加一条记录。"""

QUIZZES = [
    {
        'id': '001',
        'title': 'LLM 练习 001',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_oop_quiz_history',
        'save_key': 'py_day01_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '002',
        'title': 'LLM 练习 002',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day02_quiz_history',
        'save_key': 'py_day02_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '003',
        'title': 'LLM 练习 003',
        'subtitle': '34 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day03_quiz_history',
        'save_key': 'py_day03_saves',
        'obj_total': 20,
        'subj_total': 14,
    },
    {
        'id': '004',
        'title': 'LLM 练习 004',
        'subtitle': '33 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day04_quiz_history',
        'save_key': 'py_day04_saves',
        'obj_total': 20,
        'subj_total': 13,
    },
    {
        'id': '005',
        'title': 'LLM 练习 005',
        'subtitle': '34 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day05_quiz_history',
        'save_key': 'py_day05_saves',
        'obj_total': 20,
        'subj_total': 14,
    },
    {
        'id': '006',
        'title': 'LLM 练习 006',
        'subtitle': '32 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day05_sup_quiz_history',
        'save_key': 'py_day05_sup_saves',
        'obj_total': 20,
        'subj_total': 12,
    },
    {
        'id': '007',
        'title': 'LLM 练习 007',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day06_quiz_history',
        'save_key': 'py_day06_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '008',
        'title': 'LLM 练习 008',
        'subtitle': '32 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day06_new_quiz_history',
        'save_key': 'py_day06_new_saves',
        'obj_total': 20,
        'subj_total': 12,
    },
    {
        'id': '009',
        'title': 'LLM 练习 009',
        'subtitle': '30 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day06_sup_quiz_history',
        'save_key': 'py_day06_sup_saves',
        'obj_total': 20,
        'subj_total': 10,
    },
    {
        'id': '010',
        'title': 'LLM 练习 010',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day08_quiz_history',
        'save_key': 'py_day08_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '011',
        'title': 'LLM 练习 011',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day09_quiz_history',
        'save_key': 'py_day09_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '012',
        'title': 'LLM 练习 012',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_day10_quiz_history',
        'save_key': 'py_day10_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '013',
        'title': 'LLM 练习 013',
        'subtitle': '38 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_s2_day01_quiz_history',
        'save_key': 'py_s2_day01_saves',
        'obj_total': 20,
        'subj_total': 18,
    },
    {
        'id': '014',
        'title': 'LLM 练习 014',
        'subtitle': '37 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_s2_day02_quiz_history',
        'save_key': 'py_s2_day02_saves',
        'obj_total': 20,
        'subj_total': 17,
    },
    {
        'id': '015',
        'title': 'LLM 练习 015',
        'subtitle': '37 道题 · 选择题 + 填空题 + 简答题 + 代码实战',
        'storage_key': 'py_s2_day03_quiz_history',
        'save_key': 'py_s2_day03_saves',
        'obj_total': 20,
        'subj_total': 17,
    },
]
