#!/usr/bin/env python3
"""练习 003 的题目数据（从 HTML 提取）。"""

choices = [
    {'qid': 1, 'question': '闭包的三大构成条件是（ ）。', 'options': ['有循环、有判断、有返回', '有嵌套、有引用、有返回', '有参数、有注释、有调用', '有类、有对象、有继承'], 'answer': 'B', 'analysis': '闭包三条件：有嵌套（外部函数包含内部函数）、有引用（内部函数引用外部变量）、有返回（外部函数返回内部函数名）。'},
    {'qid': 2, 'question': '下列属于闭包语法核心的是（ ）。', 'options': ['外部函数返回内部函数名', '内部函数必须无参', '外部函数必须是全局函数', '内部函数必须使用 global'], 'answer': 'A', 'analysis': '闭包的核心是外部函数返回内部函数名（函数引用），这样外部才能调用内部函数并保留闭包环境。'},
    {'qid': 3, 'question': '闭包最典型的作用是（ ）。', 'options': ['提高网络速度', '保存外层变量并延长其生命周期', '自动生成类', '替代 if 判断'], 'answer': 'B', 'analysis': '闭包让内部函数持有外层变量的引用，即使外层函数执行完毕，变量仍不会销毁，延长了其生命周期。'},
    {'qid': 4, 'question': '在内部函数中修改外层（非全局）变量应使用（ ）。', 'options': ['<code>global</code>', '<code>nonlocal</code>', '<code>static</code>', '<code>lambda</code>'], 'answer': 'B', 'analysis': '<code>nonlocal</code> 用于在内部函数中声明要修改的外层（非全局）变量，<code>global</code> 用于全局变量。'},
    {'qid': 5, 'question': '装饰器的本质是（ ）。', 'options': ['继承', '闭包函数', '递归函数', '抽象类'], 'answer': 'B', 'analysis': '装饰器本质是一个接收函数、返回新函数的闭包，利用闭包特性在原函数基础上增加额外功能。'},
    {'qid': 6, 'question': '装饰器的核心价值是（ ）。', 'options': ['修改原函数源码实现增强', '不改原函数源码给函数增加额外功能', '让函数无法调用', '只能装饰无参函数'], 'answer': 'B', 'analysis': '装饰器的核心价值是"不改原函数源码"的前提下给函数增加额外功能，遵循开闭原则。'},
    {'qid': 7, 'question': '下列与 <code>@check</code> 等价的写法是（ ）。', 'options': ['<code>check = check(func)</code>', '<code>func = @check(func)</code>', '<code>func = check(func)</code>', '<code>@func = check</code>'], 'answer': 'C', 'analysis': '<code>@check</code> 语法糖等价于 <code>func = check(func)</code>，即把被装饰函数传给装饰器，用返回值替换原函数。'},
    {'qid': 8, 'question': '多个装饰器装饰同一个函数时，正确描述是（ ）。', 'options': ['离函数最远的先装饰', '离函数最近的先装饰', '先写的先执行原函数', '顺序固定与书写无关'], 'answer': 'B', 'analysis': '多个装饰器叠加时，离函数最近的（最下面）先装饰，执行时也先进入内层包装。'},
    {'qid': 9, 'question': '通用装饰器适配各种函数签名，推荐内部函数参数写为（ ）。', 'options': ['<code>a, b</code>', '<code>x</code>', '<code>*args, **kwargs</code>', '无参数'], 'answer': 'C', 'analysis': '<code>*args, **kwargs</code> 可以接收任意位置参数和关键字参数，使装饰器能适配各种函数签名。'},
    {'qid': 10, 'question': '带参数装饰器 <code>@logging("+")</code> 通常需要（ ）。', 'options': ['一层函数', '两层函数', '三层函数', '不需要函数'], 'answer': 'C', 'analysis': '带参数装饰器需要三层：最外层收装饰器参数，中间层收函数，最内层做包装。（外层收参数→中层收函数→内层做包装）'},
]

fills = [
    {'qid': 11, 'question': '闭包定义中，外层函数返回的是内部函数的（<input type="text" class="blank-input">），而不是执行结果。', 'answer': '函数名（函数地址）', 'analysis': '外层函数通过 <code>return func_inner</code> 返回内部函数的引用（函数名），而不是调用结果 <code>func_inner()</code>。'},
    {'qid': 12, 'question': '闭包三条件是有嵌套、有引用、有（<input type="text" class="blank-input">）。', 'answer': '返回', 'analysis': '闭包三条件：有嵌套（外部含内部）、有引用（内部引用外部变量）、有返回（外部返回内部函数）。'},
    {'qid': 13, 'question': '在内部函数中修改外层变量时，需先用关键字（<input type="text" class="blank-input">）声明。', 'answer': 'nonlocal', 'analysis': '<code>nonlocal</code> 告诉 Python 解释器"我要修改的是外层函数的变量，不是新建局部变量"。'},
    {'qid': 14, 'question': '装饰器是"接收函数并返回新函数"的一种（<input type="text" class="blank-input">）。', 'answer': '闭包', 'analysis': '装饰器本质上是一种特殊的闭包，接收函数作为参数，返回增强后的新函数。'},
    {'qid': 15, 'question': '装饰器语法糖 <code>@deco</code> 等价于 <code>函数名 = （<input type="text" class="blank-input">）</code>。', 'answer': 'deco(函数名)', 'analysis': '<code>@deco</code> 装饰 <code>func</code> 等价于 <code>func = deco(func)</code>，是语法层面的简化写法。'},
    {'qid': 16, 'question': '当原函数有返回值时，装饰器内部函数也应（<input type="text" class="blank-input">）原函数结果。', 'answer': '返回（return）', 'analysis': '为保持原函数行为，装饰器内部函数必须 <code>return</code> 被装饰函数的返回值，否则会丢失数据。'},
    {'qid': 17, 'question': '多个装饰器修饰同一函数时，装饰过程是由（<input type="text" class="blank-input">）到（<input type="text" class="blank-input">）。', 'answer': '内；外', 'analysis': '装饰顺序由内到外（离函数最近的先装饰），但包裹后执行顺序也先进入最内层包装。'},
    {'qid': 18, 'question': '通用装饰器常见模板中，参数接收写成（<input type="text" class="blank-input">）与（<input type="text" class="blank-input">）。', 'answer': '*args；**kwargs', 'analysis': '<code>*args</code> 接收任意位置参数，<code>**kwargs</code> 接收任意关键字参数，确保装饰器通用性。'},
    {'qid': 19, 'question': '带参数装饰器语法糖通常是"外层收参数，中层收函数，内层做包装"的（<input type="text" class="blank-input">）层结构。', 'answer': '三', 'analysis': '带参数装饰器需要三层嵌套：最外层接收装饰器参数 → 中间层接收函数 → 最内层实现包装逻辑。'},
    {'qid': 20, 'question': '装饰器常见业务场景包括日志、权限、（<input type="text" class="blank-input">）统计。', 'answer': '耗时', 'analysis': '装饰器典型场景：登录校验、权限控制、日志记录、耗时统计、异常兜底等。'},
]

shorts = [
    {'qid': 21, 'question': '用自己的话解释"为什么闭包能让外层变量在函数结束后仍可用"。', 'reference': '内部函数持续引用外层变量，导致变量随闭包一起被保留，不会被垃圾回收，生命周期被延长。'},
    {'qid': 22, 'question': '<code>global</code> 和 <code>nonlocal</code> 有什么本质区别？分别作用于哪一层变量？', 'reference': '<code>global</code> 操作全局变量（模块级别），<code>nonlocal</code> 操作外层函数（非全局）变量。两者作用域层级不同。'},
    {'qid': 23, 'question': '为什么说"所有装饰器都是闭包，但不是所有闭包都是装饰器"？', 'reference': '装饰器满足闭包结构（嵌套+引用+返回）且必须"接收函数并增强返回"。普通闭包不一定接收函数，也不一定增强行为。'},
    {'qid': 24, 'question': '装饰器在企业开发中有哪些典型应用场景？至少举 3 个。', 'reference': '常见场景：登录校验、权限控制、日志记录、耗时统计、异常兜底。装饰器是 AOP（面向切面编程）在 Python 中的重要实现。'},
    {'qid': 25, 'question': '多个装饰器叠加时，书写顺序和执行顺序如何理解？', 'reference': '书写从上到下，装饰从内到外；离函数最近的先装饰，执行链也先进入内层包装。例如 <code>@deco1 @deco2</code>，deco2 先装饰。'},
    {'qid': 26, 'question': '为什么通用装饰器必须关注"参数对齐 + 返回值对齐"？', 'reference': '不对齐会导致参数丢失或返回值被吞，原函数行为被破坏。通用装饰器必须用 <code>*args, **kwargs</code> 保证参数通透，用 <code>return</code> 保证返回值不丢失。'},
]

writes = [
    {'qid': 27, 'title': '闭包基础（必做）', 'desc': '定义外部函数 <code>func_out(num1)</code>，内部函数 <code>func_inner(num2)</code>。<br>内部函数使用外部变量完成求和并打印。<br>外部函数返回内部函数，创建闭包并调用。<br>解释每一行如何对应"有嵌套/有引用/有返回"三条件。', 'reference': '<pre>def func_out(num1):\n    def func_inner(num2):\n        # 内部函数引用了外层变量 num1 ——"有引用"\n        print("结果:", num1 + num2)\n    # 外部函数返回内部函数名 ——"有返回"\n    return func_inner\n\n# 创建闭包：num1=10 被内部函数"记住"\nf = func_out(10)\n# 调用闭包，num2=5\nf(5)   # 输出：结果: 15</pre>'},
    {'qid': 28, 'title': 'nonlocal 闭包计数器（必做）', 'desc': '编写 <code>counter()</code>，外层定义 <code>count = 0</code>。<br>内层函数每调用一次 <code>count + 1</code> 并返回新值。<br>必须使用 <code>nonlocal</code>，并连续调用至少 3 次验证状态被保存。', 'reference': '<pre>def counter():\n    count = 0\n    def add_one():\n        # nonlocal 声明要修改外层变量\n        nonlocal count\n        count += 1\n        return count\n    return add_one\n\nc = counter()\nprint(c(), c(), c())  # 输出: 1 2 3</pre>'},
    {'qid': 29, 'title': '装饰器原始写法与语法糖（必做）', 'desc': '定义登录校验装饰器 <code>check</code>。<br>用原始方式 <code>comment = check(comment)</code> 装饰一次。<br>再用 <code>@check</code> 语法糖装饰另一个函数。<br>对比两种写法并在注释中写出"等价关系"。', 'reference': '<pre>def check(fn):\n    def inner():\n        print("请先登录")\n        fn()\n    return inner\n\ndef comment():\n    print("发表评论")\n\n# 原始方式：手动调用装饰器\ncomment = check(comment)\ncomment()\n\n# 语法糖方式：@check 等价于 like = check(like)\n@check\ndef like():\n    print("点赞")\nlike()</pre>'},
    {'qid': 30, 'title': '通用装饰器（重点必做）', 'desc': '编写一个通用装饰器，内部函数使用 <code>*args, **kwargs</code>。<br>要求可装饰四类函数：1) 无参无返回 2) 有参无返回 3) 无参有返回 4) 有参有返回（含关键字参数）。<br>演示调用结果，证明"参数和返回值都不丢失"。', 'reference': '<pre>def universal_decorator(func):\n    def inner(*args, **kwargs):\n        print(">>> 增强逻辑开始")\n        # 透传所有参数并接收返回值\n        result = func(*args, **kwargs)\n        print(">>> 增强逻辑结束")\n        # 必须 return 保证返回值不丢失\n        return result\n    return inner\n\n# 测试四类函数\n@universal_decorator\ndef test1(): print("无参无返回")\n@universal_decorator\ndef test2(name): print(f"有参: {name}")\n@universal_decorator\ndef test3(): return "有返回"\n@universal_decorator\ndef test4(a, b, c=0): return a + b + c\n\ntest1()\ntest2("张三")\nprint(test3())  # 输出: 有返回\nprint(test4(1, 2, c=3))  # 输出: 6</pre>'},
    {'qid': 31, 'title': '多装饰器执行顺序（重点必做）', 'desc': '定义两个装饰器 <code>deco1</code>、<code>deco2</code>，分别打印"前/后"日志。<br>同时装饰一个函数，观察执行顺序。<br>用注释写清楚：谁先装饰、谁先执行。', 'reference': '<pre>def deco1(fn):\n    def inner():\n        print("deco1 前")\n        fn()\n        print("deco1 后")\n    return inner\n\ndef deco2(fn):\n    def inner():\n        print("deco2 前")\n        fn()\n        print("deco2 后")\n    return inner\n\n# deco2 离函数最近，先装饰（先包裹）\n# 执行顺序：deco1前 → deco2前 → 原函数 → deco2后 → deco1后\n@deco1\n@deco2\ndef work():\n    print("原函数执行")\n\nwork()\n# 输出：\n# deco1 前\n# deco2 前\n# 原函数执行\n# deco2 后\n# deco1 后</pre>'},
    {'qid': 32, 'title': '带参数装饰器（重点必做）', 'desc': "编写 <code>logging(flag)</code>：当 flag 为 <code>'+'</code> 提示加法日志，<code>'-'</code> 提示减法日志。<br>用 <code>@logging('+')</code> 装饰 <code>add(a,b)</code>。<br>用 <code>@logging('-')</code> 装饰 <code>sub(a,b)</code>。<br>输出运算结果并验证装饰器参数生效。", 'reference': '<pre>def logging(flag):\n    """最外层接收装饰器参数"""\n    def decorator(fn):\n        """中间层接收被装饰函数"""\n        def inner(a, b):\n            """最内层做实际包装"""\n            if flag == "+":\n                print("正在进行加法计算")\n            elif flag == "-":\n                print("正在进行减法计算")\n            # 调用原函数并返回结果\n            return fn(a, b)\n        return inner\n    return decorator\n\n@logging("+")\ndef add(a, b):\n    return a + b\n\n@logging("-")\ndef sub(a, b):\n    return a - b\n\nprint(add(1, 3))  # 输出: 正在进行加法计算 / 4\nprint(sub(5, 2))  # 输出: 正在进行减法计算 / 3</pre>'},
    {'qid': 33, 'title': '挑战题：函数耗时统计装饰器', 'desc': '实现一个"函数耗时统计装饰器"，输出函数名和执行时长。<br>提示：使用 <code>time.time()</code> 记录开始和结束时间，计算差值。', 'reference': '<pre>import time\n\ndef timer(func):\n    def inner(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        end = time.time()\n        print(f"函数 {func.__name__} 执行耗时: {end - start:.4f} 秒")\n        return result\n    return inner\n\n@timer\ndef slow_func():\n    total = 0\n    for i in range(1000000):\n        total += i\n    return total\n\nprint(slow_func())</pre>'},
    {'qid': 34, 'title': '挑战题：权限装饰器', 'desc': '实现一个"权限装饰器"：未登录拒绝执行，登录后放行。<br>提示：用一个全局变量模拟登录状态，装饰器内部判断状态后决定是否调用原函数。', 'reference': '<pre># 模拟登录状态\nis_login = False\n\ndef login_required(func):\n    def inner(*args, **kwargs):\n        if is_login:\n            return func(*args, **kwargs)\n        else:\n            print("请先登录后再操作！")\n    return inner\n\n@login_required\ndef view_secret():\n    print("这是机密内容...")\n\n# 未登录调用\nview_secret()  # 输出: 请先登录后再操作！\n\n# 登录后调用\nis_login = True\nview_secret()  # 输出: 这是机密内容...</pre>'},
]
