#!/usr/bin/env python3
"""练习 002 的题目数据（从 HTML 提取）。"""

choices = [
    {'qid': 1, 'question': '面向对象中，封装主要解决的问题是？', 'options': ['让所有代码都不能被访问', '数据和行为的组织，以及访问边界控制', '让类不能被继承', '让程序只能按顺序执行'], 'answer': 'B', 'analysis': '封装的核心是把相关的数据和操作方法组织到类里，同时用私有属性和公共接口控制外部访问方式（访问边界）。'},
    {'qid': 2, 'question': '下列关于继承的说法正确的是？', 'options': ['子类不能使用父类方法', '继承可以减少重复代码，并让子类复用父类能力', '继承会让所有类完全一样', 'Python 不支持继承'], 'answer': 'B', 'analysis': '继承的核心价值就是复用。子类继承父类后自动获得父类的属性和方法，避免重复编写相同代码。'},
    {'qid': 3, 'question': '定义 <code>Dog</code> 类继承 <code>Animal</code> 类，正确写法是？', 'options': ['`class Dog[Animal]:`', '`class Dog(Animal):`', '`class Dog:Animal`', '`class Dog extends Animal:`'], 'answer': 'B', 'analysis': 'Python 继承语法：<code>class 子类名(父类名):</code>。注意是圆括号。'},
    {'qid': 4, 'question': '子类重新定义父类同名方法，这种行为叫？', 'options': ['方法删除', '方法重写', '方法导入', '方法隐藏文件'], 'answer': 'B', 'analysis': '方法重写（Override）是子类定义与父类同名的方法，从而在子类中提供不同的实现。'},
    {'qid': 5, 'question': '子类重写父类方法后，子类对象调用该同名方法时，默认会优先执行？', 'options': ['子类自己的方法', '父类的方法', '随机方法', '`object` 中的方法'], 'answer': 'A', 'analysis': '方法查找遵循「就近原则」：先在子类自身查找，找到即停止，找不到才去父类。'},
    {'qid': 6, 'question': '在 Python3 中，子类调用父类初始化方法，推荐写法是？', 'options': ['`super().__init__(参数)`', '`super(self).__init__(参数)`', '`父类.__init__(参数)`', '`self.super().__init__(参数)`'], 'answer': 'A', 'analysis': 'Python3 推荐 <code>super().__init__(参数)</code>，不需要手动传 self。'},
    {'qid': 7, 'question': '多继承中，如果多个父类有同名方法，排查调用顺序应查看？', 'options': ['`类名.path()`', '`类名.mro()`', '`类名.route()`', '`类名.order()`'], 'answer': 'B', 'analysis': 'MRO（Method Resolution Order）可用 <code>类名.mro()</code> 或 <code>类名.__mro__</code> 查看。不要靠感觉猜测。'},
    {'qid': 8, 'question': 'Python 中常说的"鸭子类型"强调的是？', 'options': ['对象必须来自同一个父类', '只要有相同的方法，就可以被调用', '必须先写接口文件', '变量必须提前声明类型'], 'answer': 'B', 'analysis': '鸭子类型核心：「如果它走路像鸭子，叫起来像鸭子，那它就是鸭子」。不强制继承关系，只关心对象有没有需要的方法。'},
    {'qid': 9, 'question': '类方法需要使用的装饰器是？', 'options': ['`@staticmethod`', '`@classmethod`', '`@propertyonly`', '`@selfmethod`'], 'answer': 'B', 'analysis': '类方法使用 <code>@classmethod</code> 装饰器，第一个参数约定为 <code>cls</code>。'},
    {'qid': 10, 'question': '静态方法的特点是？', 'options': ['必须使用 `self`', '必须使用 `cls`', '通常不依赖实例属性，也不依赖类属性', '只能通过对象调用，不能通过类调用'], 'answer': 'C', 'analysis': '静态方法不需要 <code>self</code> 或 <code>cls</code>，就是放在类里的普通函数。可通过对象或类名调用。'},
]

fills = [
    {'qid': 11, 'question': '面向对象三大特性是 <input type="text" class="blank-input">、<input type="text" class="blank-input">、<input type="text" class="blank-input">。', 'answer': '封装,继承,多态', 'analysis': '三大特性：<strong>封装</strong>（数据安全）、<strong>继承</strong>（代码复用）、<strong>多态</strong>（灵活扩展）。'},
    {'qid': 12, 'question': '私有属性通常在属性名前加 <input type="text" class="blank-input">。', 'answer': '__', 'analysis': '答案为 <code>__</code>（双下划线）。如 <code>self.__balance = 0</code>。'},
    {'qid': 13, 'question': '如果想在类外安全读取私有属性，通常可以提供 <input type="text" class="blank-input"> 方法。', 'answer': 'get_xx()', 'analysis': '答案为 <code>get_xx()</code>（如 <code>get_balance()</code>）。通过 getter 方法安全读取私有属性。'},
    {'qid': 14, 'question': '如果想在类外安全修改私有属性，通常可以提供 <input type="text" class="blank-input"> 方法，并在方法中做校验。', 'answer': 'set_xx()', 'analysis': '答案为 <code>set_xx()</code>。在 setter 中校验类型和范围，防止非法数据。'},
    {'qid': 15, 'question': '子类继承父类的格式是：<code>class 子类名(</code><input type="text" class="blank-input"><code>):</code>', 'answer': '父类名', 'analysis': '答案为「父类名」。括号中写要继承的父类名称。'},
    {'qid': 16, 'question': '子类重新定义父类同名方法，叫方法 <input type="text" class="blank-input">。', 'answer': '重写', 'analysis': '答案为「重写」（Override）。调用时优先执行子类版本。'},
    {'qid': 17, 'question': '<code>super().__init__(name, hp)</code> 调用的是 <input type="text" class="blank-input"> 类的初始化方法。', 'answer': '父', 'analysis': '答案为「父」。<code>super()</code> 代表当前类的父类。'},
    {'qid': 18, 'question': '多继承中查看方法解析顺序的两种写法是 <code>类名.mro()</code> 和 <code>类名.</code><input type="text" class="blank-input"><code></code>。', 'answer': '__mro__', 'analysis': '答案为 <code>__mro__</code>。<code>类名.mro()</code> 返回列表，<code>类名.__mro__</code> 返回元组。'},
    {'qid': 19, 'question': '类方法需要装饰器 <input type="text" class="blank-input">，第一个参数通常写作 <code>cls</code>。', 'answer': '@classmethod', 'analysis': '答案为 <code>@classmethod</code>。类方法第一个参数 <code>cls</code> 代表类本身。'},
    {'qid': 20, 'question': '静态方法需要装饰器 <input type="text" class="blank-input">，通常不需要写 <code>self</code> 或 <code>cls</code>。', 'answer': '@staticmethod', 'analysis': '答案为 <code>@staticmethod</code>。静态方法不依赖实例或类属性。'},
]

shorts = [
    {'qid': 21, 'question': '什么是封装？封装有什么好处？', 'reference': '封装是把属性和方法组织到类里，并控制外部访问方式。好处是让代码结构更清晰，重要数据更安全（私有属性不被外部随意修改），外部使用更简单（通过公共方法调用）。'},
    {'qid': 22, 'question': '私有属性是不是意味着外部完全不能使用这个数据？为什么？', 'reference': '不是。私有属性只是外部不应该直接访问，但可以通过类提供的公共方法（如 <code>get_balance()</code>）间接使用。'},
    {'qid': 23, 'question': '为什么 <code>set_xx()</code> 方法中通常要做数据校验？', 'reference': '因为直接修改可能产生非法数据（负数余额、错误年龄）。<code>set_xx()</code> 可以统一做类型检查、范围校验，在修改前拦截不合理数据。'},
    {'qid': 24, 'question': '什么是继承？继承的主要好处是什么？', 'reference': '继承是子类自动获得父类已有属性和方法的机制。主要好处是减少重复代码，提高复用性。'},
    {'qid': 25, 'question': '子类继承父类后，是否只能使用父类已有功能？为什么？', 'reference': '不是。子类可以：①使用父类已有功能（继承）；②新增自己的方法（扩展）；③重写父类方法（覆盖）。'},
    {'qid': 26, 'question': '什么是方法重写？什么时候需要方法重写？', 'reference': '方法重写是子类重新定义父类同名方法。当父类方法不能满足子类需求时（比如需要不同的输出格式），就需要重写。'},
    {'qid': 27, 'question': '<code>super()</code> 的作用是什么？常见使用场景是什么？', 'reference': '<code>super()</code> 用于在子类中调用父类方法。最常见场景：子类重写 <code>__init__</code> 后，用 <code>super().__init__()</code> 复用父类初始化逻辑。'},
    {'qid': 28, 'question': '多继承出现同名方法冲突时，为什么不能靠猜？', 'reference': '因为多继承的查找顺序由 MRO 决定，不同继承顺序会影响结果。应使用 <code>类名.mro()</code> 查看真实的调用顺序。'},
    {'qid': 29, 'question': '什么是多态？多态有什么好处？', 'reference': '多态是同一个调用入口，传入不同对象，表现出不同结果。好处：调用统一，减少 if/else 分支判断，方便扩展新类型。'},
    {'qid': 30, 'question': '如何判断一个方法应该写成成员方法、类方法还是静态方法？', 'reference': '<strong>口诀</strong>：需要对象数据（self）→成员方法；需要类数据（cls）→类方法；都不需要→静态方法。'},
]

writes = [
    {'qid': 31, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">Wallet:\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, username, balance):\n        <span class="kw">self.username = username\n        <span class="kw">self.__balance = balance\n\n    <span class="kw">def <span class="fn">get_balance(<span class="kw">self):\n        <span class="kw">return <span class="kw">self.__balance\n\n    <span class="kw">def <span class="fn">deposit(<span class="kw">self, money):\n        <span class="kw">if money <= <span class="num">0:\n            <span class="fn">print(<span class="str">"存钱金额必须大于0")\n            <span class="kw">return\n        <span class="kw">self.__balance += money\n        <span class="fn">print(<span class="str">f"存钱成功，当前余额：{self.__balance}")\n\n    <span class="kw">def <span class="fn">pay(<span class="kw">self, money):\n        <span class="kw">if money <= <span class="num">0:\n            <span class="fn">print(<span class="str">"付款金额必须大于0")\n            <span class="kw">return\n        <span class="kw">if money > <span class="kw">self.__balance:\n            <span class="fn">print(<span class="str">"余额不足，付款失败")\n            <span class="kw">return\n        <span class="kw">self.__balance -= money\n        <span class="fn">print(<span class="str">f"付款成功，当前余额：{self.__balance}")\n\nwallet = Wallet(<span class="str">"小明", <span class="num">100)\nwallet.deposit(<span class="num">50)\nwallet.pay(<span class="num">30)\nwallet.pay(<span class="num">1000)\n<span class="fn">print(wallet.get_balance())'},
    {'qid': 32, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">AiTool:\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, name, status):\n        <span class="kw">self.name = name\n        <span class="kw">self.status = status\n\n    <span class="kw">def <span class="fn">enable(<span class="kw">self):\n        <span class="kw">self.status = <span class="str">"启用"\n\n    <span class="kw">def <span class="fn">show_info(<span class="kw">self):\n        <span class="fn">print(<span class="str">f"工具名称：{self.name}，状态：{self.status}")\n\n<span class="kw">class <span class="fn">DifyTool(AiTool):\n    <span class="kw">def <span class="fn">run_workflow(<span class="kw">self):\n        <span class="fn">print(<span class="str">"正在运行 Dify 工作流")\n\ndify = DifyTool(<span class="str">"客服问答工作流", <span class="str">"未启用")\ndify.show_info()\ndify.enable()\ndify.show_info()\ndify.run_workflow()'},
    {'qid': 33, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">AiTool:\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, name, status):\n        <span class="kw">self.name = name\n        <span class="kw">self.status = status\n\n    <span class="kw">def <span class="fn">show_info(<span class="kw">self):\n        <span class="fn">print(<span class="str">f"工具名称：{self.name}，状态：{self.status}")\n\n<span class="kw">class <span class="fn">DifyTool(AiTool):\n    <span class="kw">def <span class="fn">show_info(<span class="kw">self):\n        <span class="fn">print(<span class="str">f"Dify 平台工具：{self.name}，当前状态：{self.status}")\n\ndify = DifyTool(<span class="str">"知识库问答", <span class="str">"启用")\ndify.show_info()  <span class="cm"># 调用子类重写后的版本'},
    {'qid': 34, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">ModelClient:\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, model_name, base_url):\n        <span class="kw">self.model_name = model_name\n        <span class="kw">self.base_url = base_url\n\n    <span class="kw">def <span class="fn">show_config(<span class="kw">self):\n        <span class="fn">print(<span class="str">f"模型名称：{self.model_name}")\n        <span class="fn">print(<span class="str">f"接口地址：{self.base_url}")\n\n<span class="kw">class <span class="fn">OpenAIClient(ModelClient):\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, model_name, base_url, api_key):\n        <span class="kw">super().__init__(model_name, base_url)\n        <span class="kw">self.api_key = api_key\n\n    <span class="kw">def <span class="fn">show_config(<span class="kw">self):\n        <span class="kw">super().show_config()\n        <span class="fn">print(<span class="str">f"密钥前4位：{self.api_key[:4]}")\n\nclient = OpenAIClient(<span class="str">"gpt-4.1", <span class="str">"https://api.openai.com", <span class="str">"sk-123456789")\nclient.show_config()'},
    {'qid': 35, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">DifyRunner:\n    <span class="kw">def <span class="fn">run(<span class="kw">self):\n        <span class="fn">print(<span class="str">"DifyRunner：运行 Dify 工作流")\n\n<span class="kw">class <span class="fn">OpenAIRunner:\n    <span class="kw">def <span class="fn">run(<span class="kw">self):\n        <span class="fn">print(<span class="str">"OpenAIRunner：调用 OpenAI 模型")\n\n<span class="kw">class <span class="fn">LocalRunner:\n    <span class="kw">def <span class="fn">run(<span class="kw">self):\n        <span class="fn">print(<span class="str">"LocalRunner：运行本地模型")\n\n<span class="kw">def <span class="fn">start_runner(runner):\n    runner.run()  <span class="cm"># 多态：不关心类型，只要有 run 方法就能调用\n\nstart_runner(DifyRunner())\nstart_runner(OpenAIRunner())\nstart_runner(LocalRunner())'},
    {'qid': 36, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">Task:\n    total_count = <span class="num">0  <span class="cm"># 类属性：全类共享\n\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, title):\n        <span class="kw">self.title = title\n        Task.total_count += <span class="num">1  <span class="cm"># 通过类名修改类属性\n\n    <span class="kw">def <span class="fn">finish(<span class="kw">self):  <span class="cm"># 成员方法：用 self\n        <span class="fn">print(<span class="str">f"任务《{self.title}》已完成")\n\n    <span class="op">@classmethod\n    <span class="kw">def <span class="fn">show_total_count(cls):  <span class="cm"># 类方法：用 cls\n        <span class="fn">print(<span class="str">f"当前任务总数：{cls.total_count}")\n\n    <span class="op">@staticmethod\n    <span class="kw">def <span class="fn">show_rule():  <span class="cm"># 静态方法：不用 self/cls\n        <span class="fn">print(<span class="str">"任务规则：创建任务后，完成时调用 finish 方法")\n\nTask.show_rule()\ntask1 = Task(<span class="str">"复习继承")\ntask2 = Task(<span class="str">"完成作业")\ntask1.finish()\ntask2.finish()\nTask.show_total_count()'},
    {'qid': 37, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">BaseTool:\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, name):\n        <span class="kw">self.name = name\n        <span class="kw">self.__enabled = <span class="kw">False  <span class="cm"># 私有状态\n\n    <span class="kw">def <span class="fn">enable(<span class="kw">self):\n        <span class="kw">self.__enabled = <span class="kw">True\n        <span class="fn">print(<span class="str">f"{self.name} 已启用")\n\n    <span class="kw">def <span class="fn">disable(<span class="kw">self):\n        <span class="kw">self.__enabled = <span class="kw">False\n        <span class="fn">print(<span class="str">f"{self.name} 已禁用")\n\n    <span class="kw">def <span class="fn">is_enabled(<span class="kw">self):\n        <span class="kw">return <span class="kw">self.__enabled\n\n<span class="kw">class <span class="fn">DifyTool(BaseTool):\n    <span class="kw">def <span class="fn">run(<span class="kw">self):\n        <span class="fn">print(<span class="str">f"{self.name} 正在运行 Dify 工作流")\n\n<span class="kw">class <span class="fn">OpenAITool(BaseTool):\n    <span class="kw">def <span class="fn">run(<span class="kw">self):\n        <span class="fn">print(<span class="str">f"{self.name} 正在调用 OpenAI 模型")\n\n<span class="kw">def <span class="fn">run_tool(tool):\n    <span class="kw">if <span class="kw">not tool.is_enabled():\n        <span class="fn">print(<span class="str">f"{tool.name} 未启用，不能运行")\n        <span class="kw">return\n    tool.run()  <span class="cm"># 多态调用\n\ndify = DifyTool(<span class="str">"客服知识库")\nopenai_tool = OpenAITool(<span class="str">"文本生成模型")\n\nrun_tool(dify)       <span class="cm"># 未启用，被拦截\ndify.enable()\nrun_tool(dify)       <span class="cm"># 启用后正常运行\n\nopenai_tool.enable()\nrun_tool(openai_tool)'},
    {'qid': 38, 'title': '', 'desc': '', 'reference': '<span class="kw">class <span class="fn">Course:\n    total_learning_minutes = <span class="num">0  <span class="cm"># 类属性：全班总时长\n\n    <span class="kw">def <span class="fn">__init__(<span class="kw">self, name, student_name):\n        <span class="kw">self.name = name\n        <span class="kw">self.student_name = student_name\n\n    <span class="kw">def <span class="fn">learn(<span class="kw">self, minutes):  <span class="cm"># 成员方法\n        <span class="kw">if minutes <= <span class="num">0:\n            <span class="fn">print(<span class="str">"学习分钟数必须大于0")\n            <span class="kw">return\n        <span class="fn">print(<span class="str">f"{self.student_name} 学习《{self.name}》{minutes}分钟")\n        Course.total_learning_minutes += minutes\n\n    <span class="op">@classmethod\n    <span class="kw">def <span class="fn">show_total_minutes(cls):  <span class="cm"># 类方法\n        <span class="fn">print(<span class="str">f"全班累计学习时长：{cls.total_learning_minutes}分钟")\n\n    <span class="op">@staticmethod\n    <span class="kw">def <span class="fn">show_rule():  <span class="cm"># 静态方法\n        <span class="fn">print(<span class="str">"学习规则：每次学习后，请记录真实学习分钟数")\n\nCourse.show_rule()\ncourse1 = Course(<span class="str">"面向对象高级", <span class="str">"小明")\ncourse2 = Course(<span class="str">"面向对象高级", <span class="str">"小红")\ncourse1.learn(<span class="num">30)\ncourse2.learn(<span class="num">45)\nCourse.show_total_minutes()  <span class="cm"># → 75分钟'},
]
