#!/usr/bin/env python3
"""练习 006 的题目数据（从 HTML 提取）。"""

choices = [
    {'qid': 1, 'question': '在 Python 中提供多线程支持的模块是（ ）。', 'options': ['<code>multiprocessing</code>', '<code>threading</code>', '<code>asyncio</code>', '<code>subprocess</code>'], 'answer': 'B', 'analysis': '<code>threading</code> 是 Python 标准库中提供多线程支持的模块。'},
    {'qid': 2, 'question': '下面哪一项是正确的创建线程对象并启动的写法（ ）。', 'options': ['<code>t = threading.Thread(target=func); t.start()</code>', '<code>t = threading.Thread(target=func()); t.start()</code>', '<code>t = threading.start(target=func)</code>', '<code>t = threading.Thread(); t.run()</code>'], 'answer': 'A', 'analysis': 'Thread 的 target 参数传函数引用（不加括号），创建后调用 start() 启动。'},
    {'qid': 3, 'question': '如果线程任务函数定义是 <code>def work(a, b)</code>，以下传参方式正确的是（ ）。', 'options': ['<code>args=[1,2]</code>', '<code>args=(1,2)</code>', '<code>kwargs=(a:1,b:2)</code>', '<code>target=work(1,2)</code>'], 'answer': 'B', 'analysis': 'args 参数接收元组。<code>(1,2)</code> 是元组，多个元素按位置对应函数形参。'},
    {'qid': 4, 'question': '关于 Python 线程间共享全局变量，说法正确的是（ ）。', 'options': ['线程之间不能共享全局变量', '线程之间共享全局变量且任何操作都不需额外同步', '线程之间共享全局变量但多线程修改同一变量时可能引发数据错误', '必须使用 global 关键字声明后线程才能共享全局变量'], 'answer': 'C', 'analysis': '线程共享全局变量，但多线程同时修改同一变量时可能出现数据竞争，需加锁同步。'},
    {'qid': 5, 'question': '互斥锁对象的类型是（ ）。', 'options': ['<code>threading.Mutex</code>', '<code>threading.Locker</code>', '<code>threading.Lock</code>', '<code>threading.Semaphore</code>'], 'answer': 'C', 'analysis': '<code>threading.Lock</code> 是互斥锁类，调用 <code>threading.Lock()</code> 创建锁对象。'},
    {'qid': 6, 'question': '死锁发生时的典型现象是（ ）。', 'options': ['线程正常运行结束', '多个线程互相等待对方释放锁，程序无法继续', '程序中所有锁同时被释放', '线程自动放弃锁并退出'], 'answer': 'B', 'analysis': '死锁是指多个线程互相等待对方持有的资源，导致所有线程都无法继续执行。'},
    {'qid': 7, 'question': '关于 CPython 的 GIL（全局解释器锁），说法错误的是（ ）。', 'options': ['GIL 使得同一时刻通常只有一个线程执行 Python 字节码', 'GIL 可以自动保护所有共享变量，多线程编程不需要额外加锁', 'GIL 是 CPython 解释器层面的设计，与用户主动创建的 Lock 不同', '受 GIL 影响多线程不能有效利用多核做计算密集型任务'], 'answer': 'B', 'analysis': 'GIL 只保证字节码级别的安全，但 non-atomic 操作仍可能出问题，仍需要用户加 Lock 保护共享数据。'},
    {'qid': 8, 'question': '生成器推导式使用的括号是（ ）。', 'options': ['中括号 []', '大括号 {}', '小括号 ()', '尖括号 <>'], 'answer': 'C', 'analysis': '生成器推导式使用<code>()</code>，列表推导式用<code>[]</code>，集合/字典推导式用<code>{}</code>。'},
    {'qid': 9, 'question': '在 <code>def</code> 函数内使用 <code>yield</code> 关键字，该函数调用时返回的是（ ）。', 'options': ['最后一个 yield 表达式的值', '一个生成器对象', '一个迭代完成的列表', '一个线程对象'], 'answer': 'B', 'analysis': '含 yield 的函数是生成器函数，调用时返回生成器对象，不立即执行函数体。'},
    {'qid': 10, 'question': '在 Python 3.5+ 中，定义协程函数使用的关键字是（ ）。', 'options': ['<code>def</code>', '<code>async def</code>', '<code>coroutine def</code>', '<code>await def</code>'], 'answer': 'B', 'analysis': 'Python 3.5+ 使用 <code>async def</code> 定义协程函数。'},
]

fills = [
    {'qid': 11, 'question': '创建线程需要先导入模块 <input type="text" class="blank-input">。', 'answer': 'threading', 'analysis': '使用 <code>import threading</code> 导入多线程模块。'},
    {'qid': 12, 'question': '线程的执行顺序由 <input type="text" class="blank-input"> 调度决定，多次运行可能不同。', 'answer': 'CPU（操作系统）', 'analysis': '线程执行顺序由 CPU 调度决定，具有不确定性。'},
    {'qid': 13, 'question': '设置子线程为 <input type="text" class="blank-input"> 后，主线程退出时子线程会自动销毁。', 'answer': '守护线程（daemon）', 'analysis': '<code>daemon=True</code> 设为守护线程，主线程退出时自动销毁。'},
    {'qid': 14, 'question': '互斥锁获取锁的方法为 <input type="text" class="blank-input">，释放锁的方法为 <input type="text" class="blank-input">。', 'answer': 'acquire()、release()', 'analysis': '<code>lock.acquire()</code> 获取锁，<code>lock.release()</code> 释放锁，推荐用 <code>with lock:</code>。'},
    {'qid': 15, 'question': '进程是操作系统 <input type="text" class="blank-input"> 分配的基本单位；线程是 <input type="text" class="blank-input"> 调度的基本单位。', 'answer': '资源、CPU', 'analysis': '进程管理资源，线程负责执行。'},
    {'qid': 16, 'question': '获取生成器下一个值可以使用内置函数 <input type="text" class="blank-input">，或使用 <input type="text" class="blank-input"> 循环遍历所有值。', 'answer': 'next()、for', 'analysis': '<code>next()</code> 手动获取，<code>for</code> 自动遍历。'},
    {'qid': 17, 'question': '<code>yield</code> 关键字的作用是 <input type="text" class="blank-input"> 和 <input type="text" class="blank-input">。', 'answer': '返回后面的值、暂停', 'analysis': 'yield 返回一个值并暂停函数执行，下次从暂停处继续。'},
    {'qid': 18, 'question': '使用 <code>async def</code> 定义的函数称为 <input type="text" class="blank-input"> 函数，调用它返回一个 <input type="text" class="blank-input">。', 'answer': '协程（异步）、协程对象', 'analysis': 'async def 定义协程函数，调用返回协程对象。'},
    {'qid': 19, 'question': '在协程中等待一个可等待对象时，使用 <input type="text" class="blank-input"> 关键字挂起当前协程。', 'answer': 'await', 'analysis': '<code>await</code> 挂起当前协程等待可等待对象完成。'},
    {'qid': 20, 'question': '启动事件循环的最常用顶层入口是 <input type="text" class="blank-input">。', 'answer': 'asyncio.run()', 'analysis': '<code>asyncio.run(main())</code> 启动事件循环运行协程。'},
]

shorts = [
    {'qid': 21, 'question': '简述使用 <code>threading</code> 模块创建并启动多个线程的三个核心步骤，并说明要注意什么。', 'reference': "三大步骤：① <code>import threading</code>；② 创建线程对象 <code>t = threading.Thread(target=函数名, args=(...), kwargs={...})</code>；③ <code>t.start()</code>。注意：<code>target</code> 传函数名<strong>不要加括号</strong>；多线程建议写在 <code>if __name__ == '__main__':</code> 下。"},
    {'qid': 22, 'question': '为什么线程之间共享全局变量可能导致数据错误？互斥锁如何解决该问题？', 'reference': '多线程同时读写全局变量时，可能出现"读—改—写"交错执行，导致实际更新丢失。互斥锁保证<strong>同一时刻只有一个线程</strong>能进入上锁区域，避免交错修改。'},
    {'qid': 23, 'question': '解释什么是生成器？生成器有哪两种创建方式？<code>yield</code> 关键字在生成器函数中有什么作用？', 'reference': '生成器是按规则<strong>逐个生成数据</strong>的机制，不一次性全部生成，可<strong>节省内存</strong>。两种创建方式：生成器推导式 <code>(表达式 for 变量 in 可迭代对象)</code> 和含 <code>yield</code> 的函数。<code>yield</code> 的作用：① 返回后面的值；② <strong>暂停</strong>函数执行，下次从暂停处继续。'},
    {'qid': 24, 'question': '什么是协程？它和生成器存在怎样的发展关系？协程的三要素分别是什么？', 'reference': '协程是<strong>协作式并发</strong>的执行单元。Python 协程由生成器发展而来：最初用 <code>yield</code> 暂停和恢复，后引入 <code>yield from</code>，最终发展为 <code>async/await</code> 语法。协程三要素：① <code>async def</code>；② <code>await</code>；③ <code>asyncio.run()</code>。'},
    {'qid': 25, 'question': '从 Python 的角度，比较进程、线程和协程在资源开销、数据共享、适用场景上的主要区别。', 'reference': '<strong>进程</strong>：资源开销大，进程间不共享全局变量，可利用多核并行，稳定性好。<strong>线程</strong>：资源开销较小，线程间共享全局变量（需注意同步），受 GIL 限制不适合 CPU 密集型计算。<strong>协程</strong>：运行在单线程内，通过事件循环调度，资源开销极小，适合大量 I/O 密集任务的并发。'},
]

writes = [
    {'qid': 26, 'title': '多线程基础练习', 'desc': '导入 <code>threading</code> 模块。<br>定义两个函数 <code>print_numbers()</code> 和 <code>print_letters()</code>，分别输出 1~5 和 A~E。<br>分别创建两个线程执行上述两个函数，并启动线程。<br>多次运行，观察输出顺序是否每次相同。', 'reference': '<span class="kw">import</span> <span class="fn">threading</span>\n<span class="kw">import</span> <span class="fn">time</span>\n\n<span class="kw">def</span> print_numbers():\n    <span class="kw">for</span> i <span class="kw">in</span> <span class="fn">range</span>(<span class="num">1</span>, <span class="num">6</span>):\n        <span class="fn">print</span>(i)\n        <span class="fn">time</span>.sleep(<span class="num">0.1</span>)\n\n<span class="kw">def</span> print_letters():\n    <span class="kw">for</span> ch <span class="kw">in</span> [<span class="str">"A"</span>, <span class="str">"B"</span>, <span class="str">"C"</span>, <span class="str">"D"</span>, <span class="str">"E"</span>]:\n        <span class="fn">print</span>(ch)\n        <span class="fn">time</span>.sleep(<span class="num">0.1</span>)\n\nt1 = <span class="fn">threading</span>.Thread(target=print_numbers)\nt2 = <span class="fn">threading</span>.Thread(target=print_letters)\nt1.start()\nt2.start()\nt1.join()\nt2.join()\n<span class="cm"># 观察结论：多次运行数字和字母的输出顺序不固定，体现线程执行的无序性。</span>'},
    {'qid': 27, 'title': '线程传参', 'desc': '定义一个函数 <code>show_info(name, age)</code>，打印"姓名：xx，年龄：yy"。<br>创建两个子线程：一个用 <code>args</code> 元组方式传递参数；另一个用 <code>kwargs</code> 字典方式传递参数。', 'reference': '<span class="kw">import</span> <span class="fn">threading</span>\n\n<span class="kw">def</span> show_info(name, age):\n    <span class="fn">print</span>(<span class="str">f"姓名：{name}，年龄：{age}"</span>)\n\n<span class="cm"># args 元组传参</span>\nt1 = <span class="fn">threading</span>.Thread(target=show_info, args=(<span class="str">"张三"</span>, <span class="num">20</span>))\n<span class="cm"># kwargs 字典传参</span>\nt2 = <span class="fn">threading</span>.Thread(target=show_info, kwargs={<span class="str">"name"</span>: <span class="str">"李四"</span>, <span class="str">"age"</span>: <span class="num">22</span>})\n\nt1.start()\nt2.start()\nt1.join()\nt2.join()'},
    {'qid': 28, 'title': '互斥锁解决数据竞争', 'desc': '定义全局变量 <code>counter = 0</code>。<br>创建互斥锁 <code>lock = threading.Lock()</code>。<br>定义 <code>increase()</code> 循环 100000 次加 1，使用互斥锁保证安全。<br>创建两个子线程执行，等待结束后打印 counter。', 'reference': '<span class="kw">import</span> <span class="fn">threading</span>\n\ncounter = <span class="num">0</span>\nlock = <span class="fn">threading</span>.Lock()\n\n<span class="kw">def</span> increase():\n    <span class="kw">global</span> counter\n    <span class="kw">for</span> _ <span class="kw">in</span> <span class="fn">range</span>(<span class="num">100000</span>):\n        lock.acquire()\n        counter += <span class="num">1</span>\n        lock.release()\n\nt1 = <span class="fn">threading</span>.Thread(target=increase)\nt2 = <span class="fn">threading</span>.Thread(target=increase)\nt1.start()\nt2.start()\nt1.join()\nt2.join()\n<span class="fn">print</span>(<span class="str">f"最终计数值：{counter}"</span>)  <span class="cm"># 预期 200000</span>'},
    {'qid': 29, 'title': '生成器函数', 'desc': '定义生成器函数 <code>fibonacci(n)</code>，生成前 n 个斐波那契数。<br>用 for 循环遍历生成器并打印。<br>再用 next() 手动获取前三个值。<br>主动尝试取值超过上限时观察 StopIteration 异常。', 'reference': '<span class="kw">def</span> fibonacci(n):\n    a, b = <span class="num">0</span>, <span class="num">1</span>\n    <span class="kw">for</span> _ <span class="kw">in</span> <span class="fn">range</span>(n):\n        <span class="kw">yield</span> a\n        a, b = b, a + b\n\n<span class="cm"># for 循环遍历</span>\n<span class="kw">for</span> num <span class="kw">in</span> fibonacci(<span class="num">10</span>):\n    <span class="fn">print</span>(num, end=<span class="str">" "</span>)\n<span class="fn">print</span>()\n\n<span class="cm"># 手动使用 next</span>\ngen = fibonacci(<span class="num">10</span>)\n<span class="fn">print</span>(<span class="fn">next</span>(gen))  <span class="cm"># 0</span>\n<span class="fn">print</span>(<span class="fn">next</span>(gen))  <span class="cm"># 1</span>\n<span class="fn">print</span>(<span class="fn">next</span>(gen))  <span class="cm"># 1</span>\n<span class="cm"># 连续调用 10 次后再 next 会抛出 StopIteration</span>'},
    {'qid': 30, 'title': '协程并发', 'desc': '使用 <code>asyncio</code> 模块。<br>定义协程函数 <code>task(name, delay)</code>，输出"开始"→ sleep →"结束"。<br>定义 main()，用 create_task 创建两个任务，await 等待完成。<br>用 asyncio.run(main()) 启动。观察并发效果。', 'reference': '<span class="kw">import</span> <span class="fn">asyncio</span>\n<span class="kw">import</span> <span class="fn">time</span>\n\n<span class="kw">async</span> <span class="kw">def</span> task(name, delay):\n    <span class="fn">print</span>(<span class="str">f"开始：{name}"</span>)\n    <span class="kw">await</span> <span class="fn">asyncio</span>.sleep(delay)\n    <span class="fn">print</span>(<span class="str">f"结束：{name}"</span>)\n\n<span class="kw">async</span> <span class="kw">def</span> main():\n    t1 = <span class="fn">asyncio</span>.create_task(task(<span class="str">"A"</span>, <span class="num">1</span>))\n    t2 = <span class="fn">asyncio</span>.create_task(task(<span class="str">"B"</span>, <span class="num">1</span>))\n    <span class="kw">await</span> t1\n    <span class="kw">await</span> t2\n\nstart = <span class="fn">time</span>.<span class="fn">time</span>()\n<span class="fn">asyncio</span>.run(main())\n<span class="fn">print</span>(<span class="str">f"总耗时：{time.time() - start:.2f}秒"</span>)\n<span class="cm"># 观察：两个任务几乎同时完成，总耗时约1秒</span>'},
    {'qid': 31, 'title': '线程安全卖票系统（挑战）', 'desc': '共有 10 张票，多个线程模拟售卖窗口。<br>每个线程循环卖票，每次 1~3 张，若剩余不够则卖完为止。<br>使用互斥锁防止超卖。<br>最终输出每个窗口卖出的票数。', 'reference': '<span class="kw">import</span> <span class="fn">threading</span>\n<span class="kw">import</span> <span class="fn">random</span>\n<span class="kw">import</span> <span class="fn">time</span>\n\ntickets = <span class="num">10</span>\nlock = <span class="fn">threading</span>.Lock()\n\n<span class="kw">def</span> sell(window_name):\n    <span class="kw">global</span> tickets\n    sold = <span class="num">0</span>\n    <span class="kw">while</span> <span class="kw">True</span>:\n        lock.acquire()\n        <span class="kw">if</span> tickets <= <span class="num">0</span>:\n            lock.release()\n            <span class="kw">break</span>\n        sell_num = <span class="fn">min</span>(<span class="fn">random</span>.randint(<span class="num">1</span>, <span class="num">3</span>), tickets)\n        tickets -= sell_num\n        sold += sell_num\n        <span class="fn">print</span>(<span class="str">f"{window_name} 卖出了 {sell_num} 张票，剩余 {tickets} 张"</span>)\n        lock.release()\n        <span class="fn">time</span>.sleep(<span class="num">0.1</span>)\n    <span class="fn">print</span>(<span class="str">f"{window_name} 总共卖出 {sold} 张票"</span>)\n\nthreads = []\n<span class="kw">for</span> i <span class="kw">in</span> <span class="fn">range</span>(<span class="num">3</span>):\n    t = <span class="fn">threading</span>.Thread(target=sell, args=(<span class="str">f"窗口{i+1}"</span>,))\n    threads.append(t)\n    t.start()\n<span class="kw">for</span> t <span class="kw">in</span> threads:\n    t.join()\n<span class="fn">print</span>(<span class="str">"所有票已售罄或卖完"</span>)'},
    {'qid': 32, 'title': '无限素数生成器（挑战）', 'desc': '编写生成器函数 <code>prime_generator()</code>，无限生成素数（从 2 开始）。<br>使用循环输出前 10 个素数。<br>再用 next() 获取第 11 个素数。', 'reference': '<span class="kw">def</span> prime_generator():\n    num = <span class="num">2</span>\n    <span class="kw">while</span> <span class="kw">True</span>:\n        is_prime = <span class="kw">True</span>\n        <span class="kw">for</span> i <span class="kw">in</span> <span class="fn">range</span>(<span class="num">2</span>, <span class="fn">int</span>(num**<span class="num">0.5</span>) + <span class="num">1</span>):\n            <span class="kw">if</span> num % i == <span class="num">0</span>:\n                is_prime = <span class="kw">False</span>\n                <span class="kw">break</span>\n        <span class="kw">if</span> is_prime:\n            <span class="kw">yield</span> num\n        num += <span class="num">1</span>\n\n<span class="cm"># 输出前10个素数</span>\ngen = prime_generator()\n<span class="fn">print</span>(<span class="str">"前10个素数："</span>, end=<span class="str">""</span>)\n<span class="kw">for</span> _ <span class="kw">in</span> <span class="fn">range</span>(<span class="num">10</span>):\n    <span class="fn">print</span>(<span class="fn">next</span>(gen), end=<span class="str">" "</span>)\n<span class="fn">print</span>()\n\n<span class="cm"># 获取第11个素数</span>\n<span class="fn">print</span>(<span class="str">f"第11个素数：{next(gen)}"</span>)'},
]
